name: Prepare environment
description: Prepares environment for test & build

runs:
  using: "composite"
  steps:
    - name: System requirements
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential \
          curl \
          git

    - name: Install Rust
      shell: bash
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        export PATH="$HOME/.cargo/bin:$PATH"
        echo "$HOME/.cargo/bin:$PATH" >> $GITHUB_PATH

    - name: Setup rust fmt
      shell: bash
      run: rustup component add rustfmt

    - name: Setup rust clippy
      shell: bash
      run: rustup component add clippy
