[package]
name = "actionocope-cli"
version = "0.1.0"
edition = "2021"

[dependencies.actionoscope]
path = ".."

[dependencies]
log = "0.4"
env_logger = "0.11.6"
clap = { version = "4.3", features = ["derive"] }
predicates = "3.1.3"

